language: android
android:
  components:
    - build-tools-29.0.3
    - android-29
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-29
    - sys-img-armeabi-v7a-android-21

env:
  global:
    # Add this
    - MALLOC_ARENA_MAX=2

sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_f761570c4ae9_key -iv $encrypted_f761570c4ae9_iv -in app/google-services.json.enc -out app/google-services.json -d
  - yes | sdkmanager "platforms;android-29"

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s "768x1280"
  - emulator -avd test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

script: ./gradlew :app:build :app:connectedDebugAndroidTest
